[package]
name = "rust-blockchain"
version = "0.1.0"
authors = ["xuorig <mgiroux0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
sha3 = "0.9"
